### PR TITLE
Coords and text fix

### PR DESCRIPTION
**Pull request by AnyTiMeG**

### CODE REVIEW

**Comment by FjamZoo** [comment]
This PR has so many issues.

1. You're running 5 threads that check items every 2.5 seconds that will litterly lagg the ENTIRE server

2. A lot of bad code practice you are using K in a for k, v loop where V is there to get rid of K (Look in discord if you need to learn more about this)

3. Very redundant code and bad refactoring, why is all the code globalized when its a single file? Make them local.

4. It forces people to use target, there's no config option for non target.

**Comment by amantu-qbit** [comment]
Eh?

**Comment by amantu-qbit** [comment]
READ THIS VERY SLOWLY AND CAREFULLY:

https://discord.com/channels/831626422232678481/855592034424193074

**Comment by FjamZoo** [comment]
Pr closed due to leaked pepe code and many issues beyond that.

**Pull request closed without merging**
